### ISSUE TITLE
Potential bug

### ISSUE THREAD

**Issue by hubert0527** [thuanz123/realfill#4]
Hi author,

Thanks for sharing the prompt implementation!

I just noticed a potential bug at https://github.com/thuanz123/realfill/blob/303634076b42bc1d89e90b1365577f66c3dd7501/train_realfill.py#L481
The target image and target weighting are randomly augmented separately, which will cause the two things misalign and leaks the info of the masked region into the model. 
You probably want to use `torchvision.tv_tensors` and `transforms_v2.RandomCrop`.

Please kindly let me know if I messed up anything, since I only read the codes and haven't run it yet.

**Comment by thuanz123** [comment]
Yes, I have known this bug when I implemented it but because the target image and target mask are both squares with same size so the augmentation has little effect on them. I just leave it like that as I dont know how to implement it properly. But thanks for your suggestion, I will look into `torchvision.tv_tensors` and `transforms_v2.RandomCrop`

**Comment by thuanz123** [comment]
Thanks for your suggestion @hubert0527, now the dataloader should be correct
